//generated by autoeda

module tb_fifo_top();

parameter DEPTH_LOG = 4;
parameter WIDTH = 8;

logic clk;
logic rst_n;
logic fifo_write_req;
logic [WIDTH - 1:0]fifo_write_data;
logic fifo_full;
logic fifo_read_req;
logic fifo_empty;
logic [WIDTH - 1:0]ram_read_data;

fifo_top #(
	.DEPTH_LOG(DEPTH_LOG),
	.WIDTH    (WIDTH)
) dut (
	.clk            (clk),
	.rst_n          (rst_n),
	.fifo_write_req (fifo_write_req),
	.fifo_write_data(fifo_write_data),
	.fifo_full      (fifo_full),
	.fifo_read_req  (fifo_read_req),
	.fifo_empty     (fifo_empty),
	.ram_read_data  (ram_read_data)
);

initial begin
	clk = 0;
	forever begin
		 #50 clk = ~clk;
	end
end

initial begin
	rst_n = 1'b1;
	#5 rst_n = 1'b0;
	#10 rst_n = 1'b1;
end

initial begin
	fifo_write_req = 'b0;
	fifo_write_data = 'b0;
	fifo_read_req = 'b0;
end

task test_normal_read_write();
	for (int i = 0; i < 2 ** DEPTH_LOG + 4; i++) begin
		fifo_write_req = 1'b1;
		fifo_write_data = (WIDTH)'(i) * 2;
		@(negedge clk);
	end
	fifo_write_req = 'b0;
	for (int i = 0; i < 2 ** DEPTH_LOG + 4; i++) begin
		fifo_read_req = 1'b1;
		@(negedge clk);
	end
	fifo_read_req = 'b0;
endtask : test_normal_read_write

task test_empty_read_write();
	for (int i = 0; i < 2 ** DEPTH_LOG; i++) begin
		fifo_write_req = 1'b1;
		fifo_read_req = 1'b1;
		fifo_write_data = (WIDTH)'(i);
		@(negedge clk);
	end
endtask : test_empty_read_write

task test_full_read_write();
	for (int i = 0; i < 2 ** DEPTH_LOG + 4; i++) begin
		fifo_write_req = 1'b1;
		fifo_write_data = (WIDTH)'(i);
		@(negedge clk);
	end
	forever begin
		fifo_write_req = 1'b1;
		fifo_read_req = 1'b1;
		fifo_write_data = (WIDTH)'($urandom_range(0,2 ** WIDTH));
		@(negedge clk);
	end
endtask : test_full_read_write

initial begin
	@(negedge clk);
	forever begin
		// test_normal_read_write();
		// test_empty_read_write();
		test_full_read_write();
	end
end

endmodule