//generated by autoeda

module tb_spi_config();

parameter SPI_MAX_WIDTH_LOG = 4;

logic clk;
logic rst_n;
logic config_req;
logic [SPI_MAX_WIDTH_LOG + 1:0]config_data;
logic cpol;
logic cpha;
logic [SPI_MAX_WIDTH_LOG - 1:0]spi_width;

spi_config #(
	.SPI_MAX_WIDTH_LOG(SPI_MAX_WIDTH_LOG)
) dut (
	.clk        (clk),
	.rst_n      (rst_n),
	.config_req (config_req),
	.config_data(config_data),
	.cpol       (cpol),
	.cpha       (cpha),
	.spi_width  (spi_width)
);

string dump_file;
initial begin
	`ifdef DUMP
		if($value$plusargs("FSDB= %s" ,dump_file))
			$display("dump_file = %s",dump_file);
		$fsdbDumpfile(dump_file);
		$fsdbDumpvars(0, tb_spi_config);
	`endif
end

`ifdef VCD_ON
	initial begin
		# <start>;
		$dumpfile("dut.vcd");
		$dumpvars(0,tb_spi_config.dut);
		# <hold>;
		$finish;
	end
`endif

initial begin
	clk = 0;
	forever begin
		 # <clock> clk = ~clk;
	end
end

initial begin
	rst_n = 1'b1;
	#5 rst_n = 1'b0
	#10 rst_n = 1'b1;
end

initial begin
	config_req = 'b0;
	config_data = 'b0;
end

endmodule