//generated by autoeda

module tb_uart();

parameter BAUD = 5207;

logic clk;
logic rst_n;
logic uart_tran;
logic send_start;
logic send_busy;
logic send_finish;
logic [7:0]send_data;
logic receive_start;
logic receive_busy;
logic receive_finish;
logic [7:0]receive_data;

uart #(
	.BAUD(BAUD)
) dut (
	.clk           (clk),
	.rst_n         (rst_n),

	.uart_din      (uart_tran),
	.uart_dout     (uart_tran),

	.send_start    (send_start),
	.send_busy     (send_busy),
	.send_finish   (send_finish),
	.send_data     (send_data),

	.receive_start (receive_start),
	.receive_busy  (receive_busy),
	.receive_finish(receive_finish),
	.receive_data  (receive_data)
);

initial begin
	clk = 0;
	forever begin
		 #50 clk = ~clk;
	end
end

initial begin
	rst_n = 1'b1;
	#5 rst_n = 1'b0;
	#10 rst_n = 1'b1;
end

initial begin
	send_start = 'b0;
	send_data = 'b0;

	forever begin
		@(negedge clk);
		send_data = 8'($urandom_range(0,256));
		send_start = 1'b1;
		@(negedge clk);
		send_start = 1'b0;

		do begin
			@(negedge clk);
		end while(receive_finish == 1'b0);

		if(receive_data == send_data) begin
			$display("successful %h -> %h",send_data,receive_data);
		end else begin
			$stop;
		end
	end
end

endmodule